

podTemplate(label: 'OnboardingWorkflow', containers: [
    containerTemplate(name: 'technical-on-boarding', image: 'docker.io/library/golang:1.8', ttyEnabled: true, command: 'cat', alwaysPullImage: true, resourceRequestMemory: '128Mi', resourceLimitMemory: '1Gi'),
  ]){

    node('OnboardingWorkflow') {
        container ('technical-on-boarding') {
            stage('checkout') {
                checkout scm
            }

            stage('docker env setup') {
                sh 'apt-get -qq update && apt-get -qq -y install build-essential'
            }

            stage('lint'){
                sh 'make -C ./onboarding lint'
            }

            stage('dependencies'){
                sh 'make -C ./onboarding deps'
            }


            stage('test'){
                sh 'make -C ./onboarding test'
            }


            stage('build'){
                sh 'make -C ./onboarding build'
            }

        }

    
    }
  }



