#!/bin/bash

# fail out if GITHUB_TOKEN isn't set
set -u

echo "This table was auto-generated by scripts/generate-repos-table.sh on $(date -u) "
echo ""

echo "| name | owner | fork  | private | description | "
echo "| ---  | ---   | ---   | ---     | ---         | "

for repo_url in \
  $(curl -s "https://api.github.com/orgs/samsung-cnct/repos?access_token=${GITHUB_TOKEN}&per_page=100" | jq -r '.[].url' | sort); do
  repo_json=$(curl -s "${repo_url}?access_token=${GITHUB_TOKEN}")
  name=$(echo ${repo_json} | jq -r '.name')
  owning_teams=$(curl -s "${repo_url}/teams?access_token=${GITHUB_TOKEN}" | jq -r '[.[] | select(.permission == "admin") | "[@samsung-cnct/\(.name)](https://github.com/orgs/samsung-cnct/teams/\(.name))"] | join(", ")')
  html_url=$(echo ${repo_json} | jq -r '.html_url')
  fork=$(echo ${repo_json} | jq -r '.fork')
  private=$(echo ${repo_json} | jq -r '.private')
  description=$(echo ${repo_json} | jq -r '.description')
  echo "| [${name}](${html_url}) | ${owning_teams} | ${fork} | ${private} | ${description} |"
done
